NotesApplication/Controllers/ThemeSwitcherController.cs
using Microsoft.AspNetCore.Mvc;
using NotesApplication.Services;

namespace NotesApplication.Controllers
{
    public class ThemeSwitcherController : Controller
    {
        private readonly IUserSettingsService _userSettingsService;

        public ThemeSwitcherController(IUserSettingsService userSettingsService)
        {
            _userSettingsService = userSettingsService;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Update(string id)
        {
            _userSettingsService.ChangeTheme(id);
            
            var referer = Request.Headers["Referer"].ToString();
            if (string.IsNullOrEmpty(referer))
            {
                referer = "/";
            }

            return Redirect(referer);
        }
    }
}

NotesApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    @inject NotesApplication.Services.IUserSettingsService UserSettingsService

    <environment include="Development">
        <link rel="stylesheet" href="~/css/bootstrap/@UserSettingsService.GetCurrentThemeKey()/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/bootstrap/@UserSettingsService.GetCurrentThemeKey()/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Notes" asp-action="Index" class="navbar-brand">Notes</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Notes" asp-action="Add">New Note</a></li>
                    <li><a asp-area="" asp-controller="Notes" asp-action="RestoreTestData">Reset TestData</a></li>
                    <li class="visible-xs"><a asp-area="" asp-controller="ThemeSwitcher" asp-action="Index">Change Theme</a></li>
                </ul>
                <div class="dropdown pull-right navbar-form hidden-xs">
                    @await Html.PartialAsync("_ThemeSwitcherDropDown")
                </div>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @Html.Partial("_StatusMessages")
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Notes</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/moment-with-locales.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/js/moment-with-locales.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)

    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

NotesApplication/Views/Shared/_StatusMessages.cshtml
@{
    var type = (string)TempData["_alert.type"];
    var title = (string)TempData["_alert.title"];
    var body = (string)TempData["_alert.body"];
}
@if (!string.IsNullOrEmpty(type))
{
    <br>
    <div class="alert alert-@type alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>@title</strong> @body
    </div>    
}

NotesApplication/Views/Shared/_ThemeSwitcherDropDown.cshtml
@inject NotesApplication.Services.IUserSettingsService UserSettingsService

<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
    @{ var themes = UserSettingsService.GetAvailableThemeLabelByKeys(); }
    @themes[UserSettingsService.GetCurrentThemeKey()]
    <span class="caret"></span>
</button>
<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    @foreach (var theme in themes)
    {
        <li role="presentation">
            <a role="menuitem" tabindex="-1" asp-area="" asp-controller="ThemeSwitcher" asp-action="Update" asp-route-id="@theme.Key">@theme.Value</a>
        </li>
    }
</ul>